# Generated by Django 6.1.1 on 2026-10-03 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('cpf', models.CharField(help_text='Somente números.', max_length=11, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='data de nascimento')),
                ('phone', models.CharField(max_length=30, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lent_date', models.DateField(verbose_name='emprestado em')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='devolução prevista')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='devolvido em')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='inventory.equipment', verbose_name='equipamento')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='lending.person', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'empréstimo',
                'verbose_name_plural': 'empréstimos',
                'constraints': [models.CheckConstraint(condition=models.Q(('due_date__isnull', True), ('due_date__gte', models.F('lent_date')), _connector='OR'), name='loan_due_not_before_lent'), models.CheckConstraint(condition=models.Q(('return_date__isnull', True), ('return_date__gte', models.F('lent_date')), _connector='OR'), name='loan_return_not_before_lent'), models.UniqueConstraint(condition=models.Q(('return_date__isnull', True)), fields=('equipment',), name='loan_one_open_per_equipment')],
            },
        ),
    ]
