# Generated by Django 6.1.1 on 2026-10-04 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_tag_status_images_specs'),
        ('lending', '0002_person_document_and_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guaranteed_loans', to='lending.person', verbose_name='fiador'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('guarantor', models.F('person')), _negated=True), name='loan_guarantor_is_not_borrower'),
        ),
    ]
