# Generated by Django 6.1.1 on 2026-10-04 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_loan_guarantor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guaranteed_loans', to='lending.person', verbose_name='solidário'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='lending.person', verbose_name='beneficiário'),
        ),
    ]
