# Generated by Django 6.1.1 on 2026-10-04 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0004_solidario_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('lent', 'Emprestado'), ('returned', 'Devolvido'), ('edited', 'Editado'), ('reopened', 'Devolução desfeita')], max_length=20, verbose_name='ação')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='alterações')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='por')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='lending.loan', verbose_name='empréstimo')),
            ],
            options={
                'verbose_name': 'registro do empréstimo',
                'verbose_name_plural': 'registros do empréstimo',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
