# Generated by Django 6.1.1 on 2026-10-04 17:24

import hospitalequip.lending.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0005_loan_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='contract',
            field=models.FileField(blank=True, storage=hospitalequip.lending.models.private_storage, upload_to=hospitalequip.lending.models.contract_path, verbose_name='contrato assinado'),
        ),
        migrations.AlterField(
            model_name='loanlog',
            name='action',
            field=models.CharField(choices=[('lent', 'Emprestado'), ('returned', 'Devolvido'), ('edited', 'Editado'), ('reopened', 'Devolução desfeita'), ('contract_added', 'Contrato anexado'), ('contract_replaced', 'Contrato substituído')], max_length=20, verbose_name='ação'),
        ),
    ]
