# Generated by Django 6.1.1 on 2026-10-04 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_tag_status_images_specs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('damaged', 'Em manutenção'), ('lost', 'Extraviado'), ('written_off', 'Baixado')], default='active', max_length=20, verbose_name='situação'),
        ),
        migrations.CreateModel(
            name='EquipmentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('active', 'Ativo'), ('damaged', 'Em manutenção'), ('lost', 'Extraviado'), ('written_off', 'Baixado')], max_length=20, verbose_name='de')),
                ('to_status', models.CharField(choices=[('active', 'Ativo'), ('damaged', 'Em manutenção'), ('lost', 'Extraviado'), ('written_off', 'Baixado')], max_length=20, verbose_name='para')),
                ('effective_on', models.DateField(verbose_name='em')),
                ('reason', models.TextField(verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='por')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_logs', to='inventory.equipment', verbose_name='equipamento')),
            ],
            options={
                'verbose_name': 'mudança de situação',
                'verbose_name_plural': 'mudanças de situação',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='status_log_changes_status')],
            },
        ),
    ]
